export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';